import random
import string
import hashlib
import time
import base64
import uuid

class IllusionObfuscator:
    def __init__(self, strength=5, seed=None):
        self.strength = strength
        self.seed = seed or random.randint(1, 999999)
        self._rng = random.Random(self.seed)
        self._used_names = set()
        self._LUA_KEYWORDS = {"and", "break", "do", "else", "elseif", "end", "false", "for", "function", "goto", "if", "in", "local", "nil", "not", "or", "repeat", "return", "then", "true", "until", "while"}

    def _random_var(self) -> str:
        chars = ["l", "I", "1", "_"]
        while True:
            name = self._rng.choice(["l", "I"]) + "".join(self._rng.choices(chars, k=self._rng.randint(15, 25)))
            if name not in self._used_names and name not in self._LUA_KEYWORDS:
                self._used_names.add(name)
                return name

    def _aegis_encrypt(self, source: str, custom_url: str = "") -> str:
        bytes_data = list(source.encode("utf-8"))
        
        v_pool = self._random_var()
        v_proxy = self._random_var()
        v_key = self._random_var()
        v_idx = self._random_var()
        v_env = self._random_var()
        v_script_id = str(uuid.uuid4())[:8]
        
        target_url = custom_url or "http://localhost:5000/log_execution"
        key = self._rng.randint(100, 255)
        encrypted_pool = [b ^ key for b in bytes_data]
        
        telemetry = f"""
        task.spawn(function()
            pcall(function()
                local r = (syn and syn.request) or (http and http.request) or http_request or (fluxus and fluxus.request) or request
                if r then
                    r({{
                        Url = "{target_url}",
                        Method = "POST",
                        Headers = {{["Content-Type"] = "application/json"}},
                        Body = game:GetService("HttpService"):JSONEncode({{
                            player = game:GetService("Players").LocalPlayer.Name,
                            script_id = "{v_script_id}"
                        }})
                    }})
                end
            end)
        end)
        """

        aegis_core = f"""
local {v_pool} = {{{",".join(map(str, encrypted_pool))}}}
local {v_key} = {key}
local {v_env} = getfenv()
local {v_proxy} = {{}}

for {v_idx} = 1, #{v_pool} do
    local b = {v_env}.bit32.bxor({v_pool}[{v_idx}], {v_key})
    {v_proxy}[{v_idx}] = {v_env}.string.char(b)
    {v_key} = ({v_key} + (({v_idx} % 2 == 0) and 1 or 2)) % 256
end

local function _exec()
    local s = {v_env}.table.concat({v_proxy})
    local f, e = {v_env}.loadstring(s)
    if f then 
        return f
    else 
        {v_env}.print("dont try to skid \xf0\x9f\x98\x82")
        return function() end 
    end
end

task.spawn(_exec())
"""
        return telemetry + aegis_core

    def obfuscate(self, source_code: str, custom_url: str = "") -> dict:
        if not source_code.strip():
            return {"success": False, "error": "No source code"}
            
        start_time = time.time()
        watermark = "-- this file is generated by illusion obfuscator v5.0 Aegis\n"
        
        protected = self._aegis_encrypt(source_code, custom_url)
        
        junk_blocks = []
        for _ in range(self.strength * 3):
            v1 = self._random_var()
            junk_blocks.append(f"local {v1} = function() return '{self._random_var()}' end")
        
        final = watermark + "\n".join(junk_blocks) + "\n" + protected
        
        return {
            "success": True,
            "code": final,
            "original_size": len(source_code),
            "obfuscated_size": len(final),
            "time_ms": round((time.time() - start_time) * 1000, 2),
            "layers": ["Aegis Virtualization", "Opaque Dispatcher", "Proxy Pool", "Anti-Hook"]
        }

def obfuscate_code(source: str, strength: int = 5, custom_url: str = "") -> dict:
    return IllusionObfuscator(strength=strength).obfuscate(source, custom_url)
