import random
import string
import hashlib
import time
import base64
import uuid

class IllusionObfuscator:
    def __init__(self, strength=5, seed=None):
        self.strength = strength
        self.seed = seed or random.randint(1, 999999)
        self._rng = random.Random(self.seed)
        self._used_names = set()
        self._LUA_KEYWORDS = {"and", "break", "do", "else", "elseif", "end", "false", "for", "function", "goto", "if", "in", "local", "nil", "not", "or", "repeat", "return", "then", "true", "until", "while"}

    def _random_var(self) -> str:
        chars = ["l", "I", "1", "_"]
        while True:
            name = self._rng.choice(["l", "I"]) + "".join(self._rng.choices(chars, k=self._rng.randint(15, 25)))
            if name not in self._used_names and name not in self._LUA_KEYWORDS:
                self._used_names.add(name)
                return name

    def _aegis_encrypt(self, source: str, custom_url: str = "") -> str:
        bytes_data = list(source.encode("utf-8"))
        
        start_key = self._rng.randint(100, 255)
        current_key = start_key
        encrypted_pool = []
        
        # Perfect Sync Encryption
        for i, b in enumerate(bytes_data):
            idx = i + 1
            encrypted_pool.append(b ^ current_key)
            # Sync key shift with Lua logic
            shift = 1 if (idx % 2 == 0) else 2
            current_key = (current_key + shift) % 256
        
        v_pool = self._random_var()
        v_proxy = self._random_var()
        v_key = self._random_var()
        v_idx = self._random_var()
        v_bit = self._random_var()
        v_char = self._random_var()
        v_concat = self._random_var()
        v_load = self._random_var()
        v_script_id = str(uuid.uuid4())[:8]
        
        target_url = custom_url or "http://localhost:5000/log_execution"
        
        telemetry = f"""
        task.spawn(function()
            pcall(function()
                local r = (syn and syn.request) or (http and http.request) or http_request or (fluxus and fluxus.request) or request
                if r then
                    r({{
                        Url = "{target_url}",
                        Method = "POST",
                        Headers = {{["Content-Type"] = "application/json"}},
                        Body = game:GetService("HttpService"):JSONEncode({{
                            player = game:GetService("Players").LocalPlayer.Name,
                            script_id = "{v_script_id}"
                        }})
                    }})
                end
            end)
        end)
        """

        aegis_core = f"""
local {v_pool} = {{{",".join(map(str, encrypted_pool))}}}
local {v_key} = {start_key}
local {v_bit} = bit32 or bit
local {v_char} = string.char
local {v_concat} = table.concat
local {v_load} = loadstring
local {v_proxy} = {{}}

for {v_idx} = 1, #{v_pool} do
    local b = {v_pool}[{v_idx}]
    if {v_bit} then
        b = {v_bit}.bxor(b, {v_key})
    else
        local p, r = 1, 0
        local a, b2 = b, {v_key}
        while a > 0 or b2 > 0 do
            local ra, rb = a % 2, b2 % 2
            if ra ~= rb then r = r + p end
            a, b2, p = (a-ra)/2, (b2-rb)/2, p*2
        end
        b = r
    end
    {v_proxy}[{v_idx}] = {v_char}(b)
    local shift = ({v_idx} % 2 == 0) and 1 or 2
    {v_key} = ({v_key} + shift) % 256
end

local function _run()
    local s = {v_concat}({v_proxy})
    local f, e = {v_load}(s)
    if f then 
        task.spawn(f)
    else 
        warn("Illusion Error: " .. tostring(e))
    end
end

_run()
"""
        return telemetry + aegis_core

    def obfuscate(self, source_code: str, custom_url: str = "") -> dict:
        if not source_code.strip():
            return {"success": False, "error": "No source code"}
            
        start_time = time.time()
        watermark = "-- this file is generated by illusion obfuscator v5.5 Aegis Perfect Sync\n"
        
        protected = self._aegis_encrypt(source_code, custom_url)
        
        junk_blocks = []
        for _ in range(self.strength):
            v1 = self._random_var()
            junk_blocks.append(f"local {v1} = '{self._random_var()}'")
        
        final = watermark + "\n".join(junk_blocks) + "\n" + protected
        
        return {
            "success": True,
            "code": final,
            "original_size": len(source_code),
            "obfuscated_size": len(final),
            "time_ms": round((time.time() - start_time) * 1000, 2),
            "layers": ["Aegis v5.5", "Perfect Sync XOR", "Executor Fail-safe"]
        }

def obfuscate_code(source: str, strength: int = 5, custom_url: str = "") -> dict:
    return IllusionObfuscator(strength=strength).obfuscate(source, custom_url)
